<a href="https://colab.research.google.com/github/audedpt/Statistical_Learning/blob/main/Python_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ISLP

# Basic commands

In [ ]:
print('fit a model with', 11, 'variables')

fit a model with 11 variabels


In [ ]:
print?

In [ ]:
3+5

8

In [ ]:
"hello" + ' '+ 'world' #Concatenation of strings

'hello world'

3 types of sequences :
* Lists
* Tuples
* Strings

## Lists [ ]

In [ ]:
x=[3,4,5]
x

[3, 4, 5]

In [ ]:
y =[4,9,7]
x+y #Concatenation of lists

[3, 4, 5, 4, 9, 7]

# Numerical Python with Numpy

In [ ]:
import numpy as np

## np.array()

array = multidimensional set of numbers

In [ ]:
x = np.array([3,4,5])#1D array
y = np.array([4,9,7])
x+y #sum of arrays

array([ 7, 13, 12])

vectors = 1D arrays np.array([ ])

matrices = 2D arrays np.array([[ ],[ ]]) or np.matrix([[ ],[ ]])

In [ ]:
x = np.array([[1,2],[3,4]]) #2D array
x

array([[1, 2],
       [3, 4]])

In [ ]:
z = np.matrix([[1,2],[3,4]])
z

matrix([[1, 2],
        [3, 4]])

### attributes of an array
x.attribute

In [ ]:
x.ndim #nbr dimension of x

2

In [ ]:
x.dtype #data type of x

dtype('int64')

In [ ]:
np.array([[1,2],[3.0,4]]).dtype

dtype('float64')

In [ ]:
np.array?

In [ ]:
np.array([[1,2],[3,4]],float).dtype

dtype('float64')

In [ ]:
x.shape #nbr rows & columns of x

(2, 2)

In [ ]:
x.sum() #sum elements of x

10

In [ ]:
np.sum(x) #sum elements of x

10

## Tuples (r,c)
specifies nbr rows and columns

In [ ]:
x = np.array([1,2,3,4,5,6])
print('beginning x:\n', x)
x_reshape = x.reshape((2,3))#reshape array 1D in new dimension
                            #tuples (2,3) specifies 2 rows and 3 columns
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


arrays are 0-based indexing

In [ ]:
x_reshape[0,0]#access row 1 column 1

1

In [ ]:
x_reshape[1,2]#access row 2 column 3

6

modifying x_reshape also modify x because the two objects occupy the same space in memory

In [ ]:
print('x before we modify x_reshape : \n', x)
print('x_Reshape before we modify x_reshape : \n', x_reshape)
x_reshape[0,0]=5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_Reshape:\n', x)

x before we modify x_reshape : 
 [1 2 3 4 5 6]
x_Reshape before we modify x_reshape : 
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_Reshape:
 [5 2 3 4 5 6]


arrays can be modified but not tuples

In [ ]:
my_tuple = (3,4,5)
my_tuple[0]=2

TypeError: ignored

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T #Transpose x_reshape matrix

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.sqrt(x)#square root of x

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
x**2 #square x

array([25,  4,  9, 16, 25, 36])

In [ ]:
x**0.5 #square root of x

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

## random data